
services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual.
    build: .
    container_name: api
    ports:
      - "8000:8000"
    # Sem a seção 'volumes', o código e o banco de dados (escola.db)
    # existirão apenas dentro do contêiner, de forma efêmera.
    # O comando de execução é herdado do 'CMD' no Dockerfile.
    volumes:
      - .:/app
    
  
